### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by weishengchong** [gplhegde/papaa-opencl#2]
make: aocl: Command not found
/usr/bin/ld: cannot find -lcnpy

**Comment by prashantrar** [comment]
Regarding make: aocl error please check whether you have the altera opencl sdk installed. If its installed please check whether aocl is in your $PATH

**Comment by weishengchong** [comment]
@prashantrar 
installed to 
(a)/home/ubuntu/altera/16.0/licenses/aocl
solve by adding (a) into .bashrc based on this [ref](http://www.armadeus.org/wiki/index.php?title=Quartus_installation_on_Linux)
```
export ALTERAPATH="/opt/quartus/altera/14.0/"
export ALTERAOCLSDKROOT="${ALTERAPATH}/hld"
export QUARTUS_ROOTDIR=${ALTERAPATH}/quartus
export QUARTUS_ROOTDIR_OVERRIDE="$QUARTUS_ROOTDIR"
export PATH=$PATH:${ALTERAPATH}/quartus/bin
export PATH=$PATH:${ALTERAPATH}/nios2eds/bin
export PATH=$PATH:${QSYS_ROOTDIR}

```
Now I am debugging error **/usr/bin/ld: cannot find -lcnpy**, [google of libcnpy](https://www.google.co.jp/search?q=libcnpy+install&ie=utf-8&oe=utf-8&client=firefox-b-ab&gfe_rd=cr&ei=Lq8pWIWGNsGQ8QfWmr6gDQ) does not help

```
g++  -g -fPIC -Ihost/inc -I../common/inc -I/home/ubuntu/altera/16.0/hld/host/include \
                        -I/home/ubuntu/altera/16.0/hld/host/include  host/src/test_fc_layer.cpp host/src/data_utils.cpp ../common/src/AOCLUtils/opencl.cpp ../common/src/AOCLUtils/options.cpp -Wl,--no-as-needed -L/home/ubuntu/altera/16.0/hld/board/s5_ref/linux64/lib -L/home/ubuntu/altera/16.0/hld/host/linux64/lib -Wl,--no-as-needed -lalteracl -laltera_s5_ref_mmd -lelf \
                        -L/home/user/workspace/libs \
                        -lrt -lopencv_core -lopencv_highgui -lopencv_imgproc **-lcnpy** \
                        -o bin/host
/usr/bin/ld: cannot find -lcnpy

```

**Comment by prashantrar** [comment]
@gplhegde @nachiram do any of you know this issue...

**Comment by weishengchong** [comment]
Thanks for support, 
I think i miss cnpy lib called from files below
./host/src/alexnet_main_opt_v0.cpp:13:#include ["cnpy.h"](https://github.com/gplhegde/papaa-opencl/blob/master/opencl-src/common/inc/cnpy.h)

**Comment by weishengchong** [comment]
since I cannot download libcnpy, trying to resolve it by building libcnpy from 
https://github.com/rogersce/cnpy

**Comment by prashantrar** [comment]
Have you tried installing python and numpy?? I think installing numpy should solve it. first install python, then python-pip and then "pip install numpy". Try this and see if its solved

**Comment by weishengchong** [comment]
solved lcnpy error by instaling cnpy through steps below
https://github.com/rogersce/cnpy
use sudo make install

ignore new warning below
/usr/bin/ld: warning: libacl_emulator_kernel_rt.so, needed by /home/ubuntu/altera/16.0/hld/host/linux64/lib/libalteracl.so, not found

**Comment by weishengchong** [comment]
@prashantrar 
thanks for support. 
I compile it without activating numpy that was installed in virtualenv. 
after make install libcnpy, hopefully solved make error because binary generated in alexnet-altera/bin/host

**Comment by prashantrar** [comment]
Ok sure. @gplhegde note this error see if it needs fixing from our side as well.
